name: Push-to-EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy to EC2 on master branch push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the files
        uses: actions/checkout@v2  # o v3 si quieres la última versión

      - name: Deploy to Server 1
        uses: easingthemes/ssh-deploy@main
        with:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_SSH_KEY }} # Clave privada SSH (¡DIRECTAMENTE en 'with'!)
          REMOTE_HOST: ${{ secrets.HOST_DNS }}      # Host o IP
          REMOTE_USER: ${{ secrets.USERNAME }}       # Usuario SSH
          TARGET: ${{ secrets.TARGET_DIR }}       # Directorio destino en EC2
          # Opcional: Script para ejecutar en el servidor (en lugar de TARGET)
          # script: |
          #   ssh -i ~/.ssh/id_rsa ubuntu@ec2-13-58-224-172.us-east-2.compute.amazonaws.com
          #   cd /var/www/html
          #   git pull origin main
          #   # ... otros comandos ...
